/* nosim C ABI. Generated by cbindgen from ffi/src; do not edit.
 *
 * Every function is thread-safe. Handles (Nosim*Handle) are created by a *_new / *_load
 * function and released by the matching *_free; passing NULL is always safe and returns an
 * error status or a zero value. On NOSIM_STATUS_* != OK, nosim_last_error() returns a
 * message valid until the next failing call on the same thread.
 */

#ifndef NOSIM_H
#define NOSIM_H

/* Generated with cbindgen:0.29.4 */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result of a fallible call.
 */
typedef enum NosimStatus {
  /**
   * Success.
   */
  NOSIM_STATUS_OK = 0,
  /**
   * A required pointer was NULL.
   */
  NOSIM_STATUS_NULL_POINTER = 1,
  /**
   * An argument was out of range or not valid UTF-8.
   */
  NOSIM_STATUS_INVALID_ARGUMENT = 2,
  /**
   * A file could not be read.
   */
  NOSIM_STATUS_IO = 3,
  /**
   * Input text did not parse.
   */
  NOSIM_STATUS_PARSE = 4,
  /**
   * Input parsed but failed validation.
   */
  NOSIM_STATUS_VALIDATION = 5,
  /**
   * The requested item does not exist.
   */
  NOSIM_STATUS_NOT_FOUND = 6,
  /**
   * The output buffer was too small; nothing was written.
   */
  NOSIM_STATUS_BUFFER_TOO_SMALL = 7,
} NosimStatus;

/**
 * Which contributed data a resolve asks for.
 */
typedef enum NosimContentKind {
  /**
   * `content.arinc_overrides`
   */
  NOSIM_CONTENT_KIND_ARINC_OVERRIDES = 0,
  /**
   * `content.spline_networks`
   */
  NOSIM_CONTENT_KIND_SPLINE_NETWORKS = 1,
} NosimContentKind;

/**
 * Deciduous canopy phase.
 */
typedef enum NosimPhase {
  /**
   * Bare branches.
   */
  NOSIM_PHASE_WINTER_DEFOLIATION = 0,
  /**
   * Leaves scaling up.
   */
  NOSIM_PHASE_SPRING_BUDDING = 1,
  /**
   * Full canopy.
   */
  NOSIM_PHASE_SUMMER_CANOPY = 2,
  /**
   * Colour transfer.
   */
  NOSIM_PHASE_AUTUMN_SENESCENCE = 3,
} NosimPhase;

/**
 * Viewer altitude regime.
 */
typedef enum NosimAltitudeBand {
  /**
   * 0 – 20 km.
   */
  NOSIM_ALTITUDE_BAND_LOW_ALTITUDE = 0,
  /**
   * 20 – 100 km.
   */
  NOSIM_ALTITUDE_BAND_STRATOSPHERE = 1,
  /**
   * 100 – 1,000 km.
   */
  NOSIM_ALTITUDE_BAND_LOW_EARTH_ORBIT = 2,
  /**
   * Beyond 1,000 km.
   */
  NOSIM_ALTITUDE_BAND_TRANSLUNAR = 3,
} NosimAltitudeBand;

/**
 * Parent inertial frame.
 */
typedef enum NosimParentFrame {
  /**
   * Barycentric.
   */
  NOSIM_PARENT_FRAME_ICRF = 0,
  /**
   * Earth-centred.
   */
  NOSIM_PARENT_FRAME_ECI = 1,
  /**
   * Moon-centred.
   */
  NOSIM_PARENT_FRAME_MCI = 2,
} NosimParentFrame;

/**
 * Floating render origin (opaque).
 */
typedef struct NosimFloatingOrigin NosimFloatingOrigin;

/**
 * Loaded scenery package (opaque). Mounting clones a reference; the handle stays valid
 * and must still be freed.
 */
typedef struct NosimPackage NosimPackage;

/**
 * Loaded star catalogue (opaque).
 */
typedef struct NosimStarCatalog NosimStarCatalog;

/**
 * Prioritised mount table (opaque).
 */
typedef struct NosimVfs NosimVfs;

/**
 * A 3-vector, metres or kilometres as each function states.
 */
typedef struct NosimVec3 {
  /**
   * X.
   */
  double x;
  /**
   * Y.
   */
  double y;
  /**
   * Z.
   */
  double z;
} NosimVec3;

/**
 * WGS84 geodetic position.
 */
typedef struct NosimGeodetic {
  /**
   * Latitude, degrees north.
   */
  double lat_deg;
  /**
   * Longitude, degrees east.
   */
  double lon_deg;
  /**
   * Ellipsoidal height, metres.
   */
  double h_m;
} NosimGeodetic;

/**
 * Spherical ecliptic coordinates: longitude and latitude in radians, distance as stated.
 */
typedef struct NosimSpherical {
  /**
   * Longitude, radians, `[0, 2π)`.
   */
  double lon;
  /**
   * Latitude, radians.
   */
  double lat;
  /**
   * Distance.
   */
  double r;
} NosimSpherical;

/**
 * Optical libration, degrees.
 */
typedef struct NosimLibration {
  /**
   * Selenographic longitude of the sub-Earth point.
   */
  double l_deg;
  /**
   * Selenographic latitude of the sub-Earth point.
   */
  double b_deg;
} NosimLibration;

/**
 * 16-byte GPU record: RA and Dec in radians (J2000), V, B−V.
 */
typedef struct NosimStarRecord {
  /**
   * Right ascension, radians.
   */
  float ra;
  /**
   * Declination, radians.
   */
  float dec;
  /**
   * Visual magnitude.
   */
  float vmag;
  /**
   * B−V (default substituted when unmeasured).
   */
  float bv;
} NosimStarRecord;

/**
 * Linear sRGB colour, each channel in `[0, 1]`.
 */
typedef struct NosimRgb {
  /**
   * Red.
   */
  float r;
  /**
   * Green.
   */
  float g;
  /**
   * Blue.
   */
  float b;
} NosimRgb;

/**
 * Full star entry.
 */
typedef struct NosimStar {
  /**
   * Harvard Revised number.
   */
  uint16_t hr;
  /**
   * True when `bv` is a catalogue value rather than the default.
   */
  bool has_bv;
  /**
   * Right ascension, J2000, radians.
   */
  double ra_rad;
  /**
   * Declination, J2000, radians.
   */
  double dec_rad;
  /**
   * Visual magnitude.
   */
  float vmag;
  /**
   * B−V colour index.
   */
  float bv;
  /**
   * Proper motion in RA (with cos δ), arcsec/yr.
   */
  float pm_ra_arcsec_yr;
  /**
   * Proper motion in Dec, arcsec/yr.
   */
  float pm_dec_arcsec_yr;
  /**
   * Blackbody temperature from B−V, K.
   */
  double temperature_k;
  /**
   * Rendering colour.
   */
  struct NosimRgb color;
} NosimStar;

/**
 * Geographic bounding box, degrees.
 */
typedef struct NosimBounds {
  /**
   * South edge.
   */
  double min_lat;
  /**
   * North edge.
   */
  double max_lat;
  /**
   * West edge.
   */
  double min_lon;
  /**
   * East edge.
   */
  double max_lon;
} NosimBounds;

/**
 * A feature tag, key and value NUL-terminated.
 */
typedef struct NosimTag {
  /**
   * Key, e.g. `highway`.
   */
  const char *key;
  /**
   * Value, e.g. `motorway`.
   */
  const char *value;
} NosimTag;

/**
 * A placed model: ids and paths are NUL-terminated and truncated to the array size.
 */
typedef struct NosimModelPlacement {
  /**
   * Model id within its package.
   */
  char id[64];
  /**
   * Owning package id.
   */
  char package_id[128];
  /**
   * Absolute path of the mesh file.
   */
  char mesh_path[512];
  /**
   * Anchor on the ellipsoid.
   */
  struct NosimGeodetic anchor;
  /**
   * Yaw, degrees clockwise from true north.
   */
  double true_heading_deg;
} NosimModelPlacement;

/**
 * Decoded PG runway record. Optional fields come with a `has_*` flag.
 */
typedef struct NosimRunwayRecord {
  /**
   * Airport ICAO identifier.
   */
  char airport_icao[5];
  /**
   * ICAO region code.
   */
  char icao_region[3];
  /**
   * Runway identifier, e.g. `RW04R`.
   */
  char runway_ident[6];
  /**
   * Length, feet.
   */
  double length_ft;
  /**
   * Bearing, degrees.
   */
  double bearing_deg;
  /**
   * Whether the bearing is true rather than magnetic.
   */
  bool bearing_is_true;
  /**
   * Threshold latitude, degrees.
   */
  double lat_deg;
  /**
   * Threshold longitude, degrees.
   */
  double lon_deg;
  /**
   * Whether `gradient_pct` is present.
   */
  bool has_gradient;
  /**
   * Gradient, percent.
   */
  double gradient_pct;
  /**
   * Threshold elevation, feet.
   */
  double threshold_elev_ft;
  /**
   * Displaced threshold distance, feet.
   */
  double displaced_threshold_ft;
  /**
   * Whether `threshold_crossing_height_ft` is present.
   */
  bool has_tch;
  /**
   * Threshold crossing height, feet.
   */
  double threshold_crossing_height_ft;
  /**
   * Width, feet.
   */
  double width_ft;
  /**
   * Whether `stopway_ft` is present.
   */
  bool has_stopway;
  /**
   * Stopway, feet.
   */
  double stopway_ft;
  /**
   * Free-text description.
   */
  char description[24];
} NosimRunwayRecord;

/**
 * Runway pavement geometry in ECEF metres.
 */
typedef struct NosimRunwayGeometry {
  /**
   * Physical pavement start.
   */
  struct NosimVec3 threshold_ecef;
  /**
   * Physical pavement end.
   */
  struct NosimVec3 reciprocal_ecef;
  /**
   * Landing threshold.
   */
  struct NosimVec3 displaced_threshold_ecef;
  /**
   * Near-left, near-right, far-right, far-left.
   */
  struct NosimVec3 corners_ecef[4];
  /**
   * Longitudinal grade, percent.
   */
  double grade_pct;
  /**
   * Distance between pavement ends.
   */
  double centerline_length_m;
} NosimRunwayGeometry;

/**
 * Local climate inputs.
 */
typedef struct NosimClimate {
  /**
   * Local temperature, °C.
   */
  double t_local_c;
  /**
   * Day of year, 1..=365.
   */
  uint32_t doy;
  /**
   * Hemisphere.
   */
  bool northern_hemisphere;
  /**
   * Precipitation falling.
   */
  bool precipitating;
} NosimClimate;

/**
 * Intelligent Driver Model parameters.
 */
typedef struct NosimIdmParams {
  /**
   * Target speed, m/s.
   */
  double v0;
  /**
   * Minimum jam distance, m.
   */
  double s0;
  /**
   * Safe time headway, s.
   */
  double t;
  /**
   * Maximum acceleration, m/s².
   */
  double a;
  /**
   * Comfortable deceleration, m/s².
   */
  double b;
  /**
   * Free-road exponent.
   */
  double delta;
} NosimIdmParams;

/**
 * MOBIL parameters.
 */
typedef struct NosimMobilParams {
  /**
   * Politeness factor.
   */
  double politeness;
  /**
   * Etiquette threshold, m/s².
   */
  double threshold;
  /**
   * Safe braking limit for the new follower, m/s².
   */
  double b_safe;
} NosimMobilParams;

/**
 * Accelerations before and after a hypothetical lane change.
 */
typedef struct NosimLaneChangeContext {
  /**
   * Own, after.
   */
  double self_new;
  /**
   * Own, before.
   */
  double self_old;
  /**
   * Target-lane follower, after.
   */
  double new_follower_new;
  /**
   * Target-lane follower, before.
   */
  double new_follower_old;
  /**
   * Current-lane follower, after.
   */
  double old_follower_new;
  /**
   * Current-lane follower, before.
   */
  double old_follower_old;
} NosimLaneChangeContext;

/**
 * Vertex-animation-texture coordinate.
 */
typedef struct NosimVatUv {
  /**
   * Column (vertex).
   */
  double u;
  /**
   * Row (frame).
   */
  double v;
} NosimVatUv;

/**
 * Hapke model parameters.
 */
typedef struct NosimHapkeParams {
  /**
   * Single-scattering albedo.
   */
  double w;
  /**
   * Opposition surge amplitude.
   */
  double b0;
  /**
   * Opposition surge width.
   */
  double h;
  /**
   * Henyey-Greenstein asymmetry.
   */
  double b;
  /**
   * Backscatter weight.
   */
  double c;
} NosimHapkeParams;

/**
 * What a band keeps resident.
 */
typedef struct NosimBandPolicy {
  /**
   * Terrain quadtree streaming.
   */
  bool stream_terrain_quadtree;
  /**
   * Roads, runways, decals.
   */
  bool render_micro_vectors;
  /**
   * IDM / ORCA agents.
   */
  bool simulate_microscopic_agents;
  /**
   * Volumetric atmosphere.
   */
  bool raymarch_atmosphere;
  /**
   * Global quad-sphere bound.
   */
  bool bind_global_quadsphere;
  /**
   * Single spheroid mesh.
   */
  bool single_spheroid_mesh;
  /**
   * DEM resolution, metres (0 = none).
   */
  double dem_resolution_m;
} NosimBandPolicy;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Message for the most recent failure on this thread, or NULL if none. Valid until the
 * next failing call on the same thread.
 */
const char *nosim_last_error(void);

/**
 * Crate version, e.g. `0.1.0`. Static storage.
 */
const char *nosim_version(void);

/**
 * ABI version; bumped on any incompatible change to the header.
 */
uint32_t nosim_abi_version(void);

/**
 * Geodetic → ECEF, metres.
 */
struct NosimVec3 nosim_geodetic_to_ecef(struct NosimGeodetic g);

/**
 * ECEF metres → geodetic.
 */
struct NosimGeodetic nosim_ecef_to_geodetic(struct NosimVec3 ecef);

/**
 * Unit ENU forward vector for a true heading in degrees clockwise from north.
 */
struct NosimVec3 nosim_heading_to_enu(double true_heading_deg);

/**
 * ECEF → ENU metres relative to `anchor`.
 */
struct NosimVec3 nosim_ecef_to_enu(struct NosimGeodetic anchor, struct NosimVec3 ecef);

/**
 * ENU metres relative to `anchor` → ECEF.
 */
struct NosimVec3 nosim_enu_to_ecef(struct NosimGeodetic anchor, struct NosimVec3 enu);

/**
 * Batch ECEF → ENU; `input` and `output` may alias.
 *
 * # Safety
 * `input` and `output` must each point to `count` elements (or be NULL when `count` is 0).
 */
enum NosimStatus nosim_ecef_to_enu_batch(struct NosimGeodetic anchor,
                                         const struct NosimVec3 *input,
                                         struct NosimVec3 *output,
                                         size_t count);

/**
 * Batch ENU → ECEF; `input` and `output` may alias.
 *
 * # Safety
 * `input` and `output` must each point to `count` elements (or be NULL when `count` is 0).
 */
enum NosimStatus nosim_enu_to_ecef_batch(struct NosimGeodetic anchor,
                                         const struct NosimVec3 *input,
                                         struct NosimVec3 *output,
                                         size_t count);

/**
 * Creates a floating origin at the camera. `threshold_m <= 0` selects the spec's 10 km.
 */
struct NosimFloatingOrigin *nosim_floating_origin_new(struct NosimVec3 camera_ecef,
                                                      double threshold_m);

/**
 * Releases a floating origin. NULL is ignored.
 *
 * # Safety
 * `h` must be NULL or a handle from [`nosim_floating_origin_new`] not yet freed.
 */
void nosim_floating_origin_free(struct NosimFloatingOrigin *h);

/**
 * Moves the camera; returns true if the origin was rebased.
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
bool nosim_floating_origin_update(struct NosimFloatingOrigin *h, struct NosimVec3 camera_ecef);

/**
 * ECEF metres → render space. Zero vector for a NULL handle.
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
struct NosimVec3 nosim_floating_origin_to_render(const struct NosimFloatingOrigin *h,
                                                 struct NosimVec3 ecef);

/**
 * Render space → ECEF metres. Zero vector for a NULL handle.
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
struct NosimVec3 nosim_floating_origin_to_ecef(const struct NosimFloatingOrigin *h,
                                               struct NosimVec3 render);

/**
 * Batch ECEF → render space; buffers may alias.
 *
 * # Safety
 * `h` must be a live handle; `input`/`output` must point to `count` elements.
 */
enum NosimStatus nosim_floating_origin_to_render_batch(const struct NosimFloatingOrigin *h,
                                                       const struct NosimVec3 *input,
                                                       struct NosimVec3 *output,
                                                       size_t count);

/**
 * Current origin in ECEF metres.
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
struct NosimVec3 nosim_floating_origin_ecef(const struct NosimFloatingOrigin *h);

/**
 * Number of times the origin has been placed (1 after creation).
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
uint32_t nosim_floating_origin_rebase_count(const struct NosimFloatingOrigin *h);

/**
 * Julian Date of a proleptic Gregorian date and UT hours.
 */
double nosim_julian_date(int32_t year, uint32_t month, uint32_t day, double ut_hours);

/**
 * 1-based day of year; 0 for an invalid month.
 */
uint32_t nosim_day_of_year(int32_t year, uint32_t month, uint32_t day);

/**
 * Solar declination, degrees, from the day of year.
 */
double nosim_solar_declination_deg(uint32_t doy);

/**
 * Sea-level temperature lapsed to altitude (6.5 °C/km).
 */
double nosim_local_temperature_c(double t_sea_level_c, double altitude_msl_m);

/**
 * Greenwich Mean Sidereal Time, degrees.
 */
double nosim_gmst_deg(double jd_ut1);

/**
 * Greenwich Apparent Sidereal Time, degrees.
 */
double nosim_gast_deg(double jd_ut1);

/**
 * ECI (equator of date) → ECEF rotation by a sidereal angle in degrees.
 */
struct NosimVec3 nosim_eci_to_ecef(struct NosimVec3 eci, double sidereal_deg);

/**
 * ECEF → ECI rotation by a sidereal angle in degrees.
 */
struct NosimVec3 nosim_ecef_to_eci(struct NosimVec3 ecef, double sidereal_deg);

/**
 * Geometric geocentric Sun, ecliptic and equinox of date; `r` in AU.
 */
struct NosimSpherical nosim_sun_geocentric(double jd_tdb);

/**
 * Geocentric Moon, mean ecliptic and equinox of date; `r` in km.
 */
struct NosimSpherical nosim_moon_geocentric(double jd_tdb);

/**
 * Geocentric Moon in the J2000 ecliptic frame, km.
 */
struct NosimVec3 nosim_moon_geocentric_j2000(double jd_tdb);

/**
 * Apparent geocentric Sun, true equator and equinox of date, km.
 */
struct NosimVec3 nosim_sun_apparent_equatorial_km(double jd_tdb);

/**
 * Apparent geocentric Moon, true equator and equinox of date, km.
 */
struct NosimVec3 nosim_moon_apparent_equatorial_km(double jd_tdb);

/**
 * Mean obliquity of the ecliptic, radians.
 */
double nosim_mean_obliquity(double jd_tdb);

/**
 * True obliquity of the ecliptic, radians.
 */
double nosim_true_obliquity(double jd_tdb);

/**
 * Nutation in longitude and obliquity, radians. Either output may be NULL.
 *
 * # Safety
 * Non-NULL outputs must be valid for writes.
 */
void nosim_nutation(double jd_tdb, double *dpsi, double *deps);

/**
 * Rotates ecliptic coordinates to equatorial by obliquity `eps` (radians).
 */
struct NosimVec3 nosim_ecliptic_to_equatorial(struct NosimVec3 v, double eps);

/**
 * Rotates equatorial coordinates to ecliptic by obliquity `eps` (radians).
 */
struct NosimVec3 nosim_equatorial_to_ecliptic(struct NosimVec3 v, double eps);

/**
 * Observer position in the equatorial frame of date, km.
 */
struct NosimVec3 nosim_observer_equatorial_km(struct NosimGeodetic observer, double gast_deg);

/**
 * Topocentric vector (km, equatorial of date) from a geocentric one.
 */
struct NosimVec3 nosim_topocentric_km(struct NosimVec3 geocentric_equatorial_km,
                                      struct NosimGeodetic observer,
                                      double gast_deg);

/**
 * Right ascension (radians, `[0, 2π)`) and declination (radians) of an equatorial vector.
 *
 * # Safety
 * Non-NULL outputs must be valid for writes.
 */
void nosim_ra_dec(struct NosimVec3 v, double *ra, double *dec);

/**
 * Phase angle at the Moon, radians; both vectors geocentric, same frame and units.
 */
double nosim_phase_angle(struct NosimVec3 sun_geocentric, struct NosimVec3 moon_geocentric);

/**
 * Illuminated fraction of the lunar disc from the phase angle (radians).
 */
double nosim_illuminated_fraction(double phase_angle_rad);

/**
 * Angle between two directions, radians.
 */
double nosim_elongation(struct NosimVec3 a, struct NosimVec3 b);

/**
 * Optical libration of the Moon.
 */
struct NosimLibration nosim_optical_libration(double jd_tdb);

/**
 * Astronomical unit in km.
 */
double nosim_au_km(void);

/**
 * Loads the packed catalogue written by `compile_bsc5`. NULL on failure.
 *
 * # Safety
 * `bytes` must point to `len` readable bytes.
 */
struct NosimStarCatalog *nosim_star_catalog_from_packed(const uint8_t *bytes, size_t len);

/**
 * Parses the CDS V/50 `catalog` text file at `path`. NULL on failure.
 *
 * # Safety
 * `path` must be a NUL-terminated string.
 */
struct NosimStarCatalog *nosim_star_catalog_load_bsc5(const char *path);

/**
 * Releases a catalogue. NULL is ignored.
 *
 * # Safety
 * `h` must be NULL or a live handle, freed once.
 */
void nosim_star_catalog_free(struct NosimStarCatalog *h);

/**
 * Number of stars with positions.
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
size_t nosim_star_catalog_count(const struct NosimStarCatalog *h);

/**
 * Fills up to `capacity` GPU records in HR order; returns the total available.
 *
 * # Safety
 * `h` must be NULL or a live handle; `out` must point to `capacity` elements.
 */
size_t nosim_star_catalog_records(const struct NosimStarCatalog *h,
                                  struct NosimStarRecord *out,
                                  size_t capacity);

/**
 * Star at `index` (0-based, HR order).
 *
 * # Safety
 * `h` must be NULL or a live handle; `out` must be valid for writes.
 */
enum NosimStatus nosim_star_catalog_star(const struct NosimStarCatalog *h,
                                         size_t index,
                                         struct NosimStar *out);

/**
 * Index of the star with Harvard Revised number `hr`, or -1.
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
ptrdiff_t nosim_star_catalog_find_hr(const struct NosimStarCatalog *h, uint16_t hr);

/**
 * Blackbody temperature from B−V (Ballesteros).
 */
double nosim_bv_to_temperature_k(double b_minus_v);

/**
 * Normalised linear sRGB of a blackbody.
 */
struct NosimRgb nosim_blackbody_linear_srgb(double temp_k);

/**
 * Normalised linear sRGB for a colour index.
 */
struct NosimRgb nosim_bv_to_linear_srgb(double b_minus_v);

/**
 * Loads and validates the package directory at `dir`. NULL on failure (see
 * [`nosim_last_error`] for the validator's report).
 *
 * # Safety
 * `dir` must be a NUL-terminated string.
 */
struct NosimPackage *nosim_package_load(const char *dir);

/**
 * Releases a package handle. NULL is ignored.
 *
 * # Safety
 * `h` must be NULL or a live handle, freed once.
 */
void nosim_package_free(struct NosimPackage *h);

/**
 * Writes the package id; returns the size needed including the NUL (0 for NULL handle).
 *
 * # Safety
 * `h` must be NULL or a live handle; `buf` must be NULL or point to `cap` bytes.
 */
size_t nosim_package_id(const struct NosimPackage *h, char *buf, size_t cap);

/**
 * Manifest priority (0 for NULL).
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
int32_t nosim_package_priority(const struct NosimPackage *h);

/**
 * Claimed bounds (zeros for NULL).
 *
 * # Safety
 * `h` must be NULL or a live handle.
 */
struct NosimBounds nosim_package_bounds(const struct NosimPackage *h);

/**
 * Creates an empty mount table.
 */
struct NosimVfs *nosim_vfs_new(void);

/**
 * Releases a mount table (packages it references stay alive until their own free).
 *
 * # Safety
 * `h` must be NULL or a live handle, freed once.
 */
void nosim_vfs_free(struct NosimVfs *h);

/**
 * Mounts a package at its default tier. A newer version of an already-mounted id
 * replaces it; the same or an older version fails with `InvalidArgument`.
 *
 * # Safety
 * Both handles must be live.
 */
enum NosimStatus nosim_vfs_mount(struct NosimVfs *vfs, const struct NosimPackage *package);

/**
 * Unmounts by package id; returns whether it was mounted.
 *
 * # Safety
 * `vfs` must be NULL or live; `package_id` a NUL-terminated string.
 */
bool nosim_vfs_unmount(struct NosimVfs *vfs, const char *package_id);

/**
 * Number of mounted packages.
 *
 * # Safety
 * `vfs` must be NULL or live.
 */
size_t nosim_vfs_mount_count(const struct NosimVfs *vfs);

/**
 * Whether a baseline feature of `layer` at the point, carrying `tags`, is masked by any
 * mounted package. `tags` may be NULL when `tag_count` is 0.
 *
 * # Safety
 * `vfs` must be NULL or live; `layer` and every tag string NUL-terminated; `tags` must
 * point to `tag_count` elements.
 */
bool nosim_vfs_is_excluded(const struct NosimVfs *vfs,
                           const char *layer,
                           double lat_deg,
                           double lon_deg,
                           const struct NosimTag *tags,
                           size_t tag_count);

/**
 * Absolute path of the highest-priority package supplying `kind` at the point. Returns
 * the size needed including the NUL, or 0 when no package provides it.
 *
 * # Safety
 * `vfs` must be NULL or live; `buf` must be NULL or point to `cap` bytes.
 */
size_t nosim_vfs_resolve(const struct NosimVfs *vfs,
                         enum NosimContentKind kind,
                         double lat_deg,
                         double lon_deg,
                         char *buf,
                         size_t cap);

/**
 * Models anchored inside `area`, in resolution order. Returns the total count; at most
 * `capacity` are written.
 *
 * # Safety
 * `vfs` must be NULL or live; `out` must point to `capacity` elements.
 */
size_t nosim_vfs_models_in(const struct NosimVfs *vfs,
                           struct NosimBounds area,
                           struct NosimModelPlacement *out,
                           size_t capacity);

/**
 * Decodes one 132-column PG record given as `len` bytes (no NUL needed).
 *
 * # Safety
 * `line` must point to `len` bytes; `out` must be valid for writes.
 */
enum NosimStatus nosim_arinc424_parse_runway(const char *line,
                                             size_t len,
                                             struct NosimRunwayRecord *out);

/**
 * Extrudes a runway along `true_heading_deg`, fitting the far end to `reciprocal_elev_m`.
 *
 * # Safety
 * `record` and `out` must be valid.
 */
enum NosimStatus nosim_runway_build(const struct NosimRunwayRecord *record,
                                    double true_heading_deg,
                                    double reciprocal_elev_m,
                                    struct NosimRunwayGeometry *out);

/**
 * Threshold bar count for a runway width in feet (FAA AC 150/5340-1).
 */
uint32_t nosim_threshold_bar_count(double width_ft);

/**
 * Opposite-end designator for an identifier such as `RW04R`; 0 if it does not parse.
 *
 * # Safety
 * `ident` must be NUL-terminated; `buf` NULL or `cap` bytes.
 */
size_t nosim_reciprocal_designator(const char *ident, char *buf, size_t cap);

/**
 * Deterministic seed for a 1e-5° cell.
 */
uint64_t nosim_spatial_seed(double lat_deg, double lon_deg, uint64_t global_salt);

/**
 * Clamped Poisson building-level estimate.
 */
uint32_t nosim_estimate_levels(uint64_t seed,
                               double lambda,
                               uint32_t min_levels,
                               uint32_t max_levels);

/**
 * Pier stations along a deck; returns the total count, writes at most `capacity`.
 * `spacing_m <= 0` selects the spec's 35 m.
 *
 * # Safety
 * `out` must point to `capacity` doubles.
 */
size_t nosim_pier_stations(double deck_length_m, double spacing_m, double *out, size_t capacity);

/**
 * Terrain flattening weight outside pavement; `falloff_m <= 0` selects the spec's 60 m.
 */
double nosim_flatten_blend(double distance_outside_m, double falloff_m);

/**
 * Phenology phase for a climate.
 */
enum NosimPhase nosim_phenology_classify(struct NosimClimate climate);

/**
 * Leaf geometry scale, 0..=1.
 */
double nosim_leaf_scale(struct NosimClimate climate);

/**
 * Whether snow is accumulating.
 */
bool nosim_snow_accumulates(struct NosimClimate climate);

/**
 * Snow coverage mask value.
 */
double nosim_snow_coverage(double normal_dot_up, double slope_threshold, double depth);

/**
 * The spec's IDM defaults for a target speed.
 */
struct NosimIdmParams nosim_idm_params_default(double v0);

/**
 * IDM acceleration behind a leader (`gap` net distance, `dv = v − v_lead`).
 */
double nosim_idm_acceleration(struct NosimIdmParams params, double v, double gap, double dv);

/**
 * IDM acceleration with no leader.
 */
double nosim_idm_free_acceleration(struct NosimIdmParams params, double v);

/**
 * The spec's MOBIL defaults.
 */
struct NosimMobilParams nosim_mobil_params_default(void);

/**
 * MOBIL lane-change decision.
 */
bool nosim_mobil_should_change(struct NosimMobilParams params, struct NosimLaneChangeContext ctx);

/**
 * VAT texel-centre address for a vertex at a time.
 */
struct NosimVatUv nosim_vat_uv(uint32_t vertex_id,
                               uint32_t total_vertices,
                               double time_s,
                               double speed,
                               double playback_rate,
                               uint32_t frame_count);

/**
 * Typical lunar highland parameters.
 */
struct NosimHapkeParams nosim_hapke_params_default(void);

/**
 * Hapke bidirectional reflectance.
 */
double nosim_hapke_reflectance(struct NosimHapkeParams params,
                               double mu0,
                               double mu,
                               double alpha_rad);

/**
 * Chapman grazing-incidence function, `x = R / H`.
 */
double nosim_chapman(double x, double theta_rad);

/**
 * Single-scatter limb inscatter for Earth's Rayleigh atmosphere.
 */
double nosim_earth_limb_inscatter(double theta_rad, double tau_zenith, double intensity);

/**
 * Band for an altitude above the surface, metres.
 */
enum NosimAltitudeBand nosim_band_for(double altitude_m);

/**
 * Residency policy for a band.
 */
struct NosimBandPolicy nosim_policy_for(enum NosimAltitudeBand band);

/**
 * Parent frame from distances to the Earth and Moon centres, metres.
 */
enum NosimParentFrame nosim_parent_frame_for(double dist_to_earth_center_m,
                                             double dist_to_moon_center_m);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NOSIM_H */
